[project]
name = "library-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "click>=8.2.1",
    "httpx>=0.28.1",
    "mcp[cli]>=1.11.0",
    "uvicorn>=0.35.0",
]
